<?php
abstract class PDOManager extends Database
{
    protected $pdo;

    public function getDB($pdo){

    }
    public function query()
    {
        parent::query(); // TODO: Change the autogenerated stub
    }
    public function prepare()
    {
        parent::prepare(); // TODO: Change the autogenerated stub
    }
    public function lastInsertId(){

    }
}
